[versions]
# Compile only
spigot = "1.21.10-R0.1-SNAPSHOT"
authlib = "1.5.25"
headdb = "1.3.2"
papi_version = "2.11.7"
bstats = "3.1.0"
annotaiton = "23.0.0"
reflection = "2.1.21"

# Implementation
adventure = "4.24.0"
via_version = "5.4.2"


[libraries]
#Core
kotlin = {module= "org.jetbrains.kotlin:kotlin-stdlib-jdk8"}
kotlin-reflection = {module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "reflection"}
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }

authlib = { module = "com.mojang:authlib", version.ref = "authlib" }
papi = { module = "me.clip:placeholderapi", version.ref = "papi_version" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-legacy = {module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure"}
headdb = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdb" }
annotation = {module = "org.jetbrains:annotations",version.ref = "annotaiton"}
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
viaversion = {module = "com.viaversion:viaversion-api", version.ref = "via_version"}